-- for reference only

SELECT
	COSMO.COSMO_TIMESTAMP,
	COSMO.CONDUCTANCE_RESULT,
	CNV.CNV_FLOWWORKS_RAINFALL,
	CNV.CNV_FLOWWORKS_TIMESTAMP
	FROM
	(
		SELECT
			NSSK_COSMO.WAGG01.ActivityStartDate as "COSMO_DATE",
			NSSK_COSMO.WAGG01.ActivityStartTime as "COSMO_TIME",
			CAST(CONCAT_WS(' ', NSSK_COSMO.WAGG01.ActivityStartDate, NSSK_COSMO.WAGG01.ActivityStartTime) as DATETIME) as "COSMO_TIMESTAMP",
			NSSK_COSMO.WAGG01.ResultValue as "CONDUCTANCE_RESULT"
			FROM NSSK_COSMO.WAGG01
			WHERE
			CAST(CONCAT_WS(' ', NSSK_COSMO.WAGG01.ActivityStartDate, NSSK_COSMO.WAGG01.ActivityStartTime) as DATETIME) > '$COSMO_START_DATETIME' AND
			CAST(CONCAT_WS(' ', NSSK_COSMO.WAGG01.ActivityStartDate, NSSK_COSMO.WAGG01.ActivityStartTime) as DATETIME) < '$COSMO_END_DATETIME' AND
			NSSK_COSMO.WAGG01.CharacteristicName = "Conductivity"
	) COSMO
	right join (
		SELECT
			NSSK_CNV_FLOWWORKS.CNVRain.MeasurementTimestamp as "CNV_FLOWWORKS_RAINFALL",
			NSSK_CNV_FLOWWORKS.CNVRain.Rainfall as "CNV_FLOWWORKS_TIMESTAMP"
			from NSSK_CNV_FLOWWORKS.CNVRain
			where
			NSSK_CNV_FLOWWORKS.CNVRain.MeasurementTimestamp > '$CNV_FLOWWORKS_START_DATETIME' AND
			NSSK_CNV_FLOWWORKS.CNVRain.MeasurementTimestamp < '$CNV_FLOWWORKS_END_DATETIME' AND
			NSSK_CNV_FLOWWORKS.CNVRain.Rainfall > 0

	) CNV
	on
	(
		ABS(
		TIMESTAMPDIFF(
			MINUTE,
			CNV.CNV_FLOWWORKS_RAINFALL,
			COSMO.COSMO_TIMESTAMP
		)) <= 5
	)
WHERE
COSMO_TIMESTAMP is not Null and
CONDUCTANCE_RESULT is not null
ORDER BY COSMO_TIMESTAMP ASC
;